title: Patrick VanMeter
description: >-
  Data Scientist | Physicist
baseurl: ""
url: "https://pdvanmeter.github.io"

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
